//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS_Website.DSS_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSS_Website.DSS_Service.SVCUser))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfTransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Transaction[] TransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Wishlist[] WishlistsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfTransactions {
            get {
                return this.NumberOfTransactionsField;
            }
            set {
                if ((this.NumberOfTransactionsField.Equals(value) != true)) {
                    this.NumberOfTransactionsField = value;
                    this.RaisePropertyChanged("NumberOfTransactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Transaction[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Wishlist[] Wishlists {
            get {
                return this.WishlistsField;
            }
            set {
                if ((object.ReferenceEquals(this.WishlistsField, value) != true)) {
                    this.WishlistsField = value;
                    this.RaisePropertyChanged("Wishlists");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SVCUser", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class SVCUser : DSS_Website.DSS_Service.User {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSS_Website.DSS_Service.SVCOrder))]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountDueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.OrderProductJoin[] OrderProductJoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AmountDue {
            get {
                return this.AmountDueField;
            }
            set {
                if ((this.AmountDueField.Equals(value) != true)) {
                    this.AmountDueField = value;
                    this.RaisePropertyChanged("AmountDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Delivery {
            get {
                return this.DeliveryField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryField, value) != true)) {
                    this.DeliveryField = value;
                    this.RaisePropertyChanged("Delivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumItems {
            get {
                return this.NumItemsField;
            }
            set {
                if ((this.NumItemsField.Equals(value) != true)) {
                    this.NumItemsField = value;
                    this.RaisePropertyChanged("NumItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.OrderProductJoin[] OrderProductJoins {
            get {
                return this.OrderProductJoinsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductJoinsField, value) != true)) {
                    this.OrderProductJoinsField = value;
                    this.RaisePropertyChanged("OrderProductJoins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.TransactionProductJoin[] TransactionProductJoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransID {
            get {
                return this.TransIDField;
            }
            set {
                if ((this.TransIDField.Equals(value) != true)) {
                    this.TransIDField = value;
                    this.RaisePropertyChanged("TransID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.TransactionProductJoin[] TransactionProductJoins {
            get {
                return this.TransactionProductJoinsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionProductJoinsField, value) != true)) {
                    this.TransactionProductJoinsField = value;
                    this.RaisePropertyChanged("TransactionProductJoins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wishlist", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class Wishlist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WishlistIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.WishlistProductJoin[] WishlistProductJoinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WishlistID {
            get {
                return this.WishlistIDField;
            }
            set {
                if ((this.WishlistIDField.Equals(value) != true)) {
                    this.WishlistIDField = value;
                    this.RaisePropertyChanged("WishlistID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.WishlistProductJoin[] WishlistProductJoins {
            get {
                return this.WishlistProductJoinsField;
            }
            set {
                if ((object.ReferenceEquals(this.WishlistProductJoinsField, value) != true)) {
                    this.WishlistProductJoinsField = value;
                    this.RaisePropertyChanged("WishlistProductJoins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SVCOrder", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class SVCOrder : DSS_Website.DSS_Service.Order {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderProductJoin", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class OrderProductJoin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSS_Website.DSS_Service.SVCProduct))]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HealthinessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfWishesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.OrderProductJoin[] OrderProductJoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrepationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityBoughtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.TransactionProductJoin[] TransactionProductJoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.WishlistProductJoin[] WishlistProductJoinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Healthiness {
            get {
                return this.HealthinessField;
            }
            set {
                if ((this.HealthinessField.Equals(value) != true)) {
                    this.HealthinessField = value;
                    this.RaisePropertyChanged("Healthiness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfWishes {
            get {
                return this.NumberOfWishesField;
            }
            set {
                if ((this.NumberOfWishesField.Equals(value) != true)) {
                    this.NumberOfWishesField = value;
                    this.RaisePropertyChanged("NumberOfWishes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.OrderProductJoin[] OrderProductJoins {
            get {
                return this.OrderProductJoinsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductJoinsField, value) != true)) {
                    this.OrderProductJoinsField = value;
                    this.RaisePropertyChanged("OrderProductJoins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrepationTime {
            get {
                return this.PrepationTimeField;
            }
            set {
                if ((this.PrepationTimeField.Equals(value) != true)) {
                    this.PrepationTimeField = value;
                    this.RaisePropertyChanged("PrepationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuantityBought {
            get {
                return this.QuantityBoughtField;
            }
            set {
                if ((this.QuantityBoughtField.Equals(value) != true)) {
                    this.QuantityBoughtField = value;
                    this.RaisePropertyChanged("QuantityBought");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.TransactionProductJoin[] TransactionProductJoins {
            get {
                return this.TransactionProductJoinsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionProductJoinsField, value) != true)) {
                    this.TransactionProductJoinsField = value;
                    this.RaisePropertyChanged("TransactionProductJoins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.WishlistProductJoin[] WishlistProductJoins {
            get {
                return this.WishlistProductJoinsField;
            }
            set {
                if ((object.ReferenceEquals(this.WishlistProductJoinsField, value) != true)) {
                    this.WishlistProductJoinsField = value;
                    this.RaisePropertyChanged("WishlistProductJoins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SVCProduct", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class SVCProduct : DSS_Website.DSS_Service.Product {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionProductJoin", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class TransactionProductJoin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Transaction TransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransID {
            get {
                return this.TransIDField;
            }
            set {
                if ((this.TransIDField.Equals(value) != true)) {
                    this.TransIDField = value;
                    this.RaisePropertyChanged("TransID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Transaction Transaction {
            get {
                return this.TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionField, value) != true)) {
                    this.TransactionField = value;
                    this.RaisePropertyChanged("Transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WishlistProductJoin", Namespace="http://schemas.datacontract.org/2004/07/DSS_Service")]
    [System.SerializableAttribute()]
    public partial class WishlistProductJoin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DSS_Website.DSS_Service.Wishlist WishlistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WishlistIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DSS_Website.DSS_Service.Wishlist Wishlist {
            get {
                return this.WishlistField;
            }
            set {
                if ((object.ReferenceEquals(this.WishlistField, value) != true)) {
                    this.WishlistField = value;
                    this.RaisePropertyChanged("Wishlist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WishlistID {
            get {
                return this.WishlistIDField;
            }
            set {
                if ((this.WishlistIDField.Equals(value) != true)) {
                    this.WishlistIDField = value;
                    this.RaisePropertyChanged("WishlistID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DSS_Service.IDSSWebService")]
    public interface IDSSWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUser", ReplyAction="http://tempuri.org/IDSSWebService/GetUserResponse")]
        DSS_Website.DSS_Service.SVCUser GetUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUser", ReplyAction="http://tempuri.org/IDSSWebService/GetUserResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUserByID", ReplyAction="http://tempuri.org/IDSSWebService/GetUserByIDResponse")]
        DSS_Website.DSS_Service.SVCUser GetUserByID(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUserByID", ReplyAction="http://tempuri.org/IDSSWebService/GetUserByIDResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetUserByIDAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetAllProducts", ReplyAction="http://tempuri.org/IDSSWebService/GetAllProductsResponse")]
        DSS_Website.DSS_Service.SVCProduct[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetAllProducts", ReplyAction="http://tempuri.org/IDSSWebService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetProducts", ReplyAction="http://tempuri.org/IDSSWebService/GetProductsResponse")]
        DSS_Website.DSS_Service.SVCProduct[] GetProducts(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetProducts", ReplyAction="http://tempuri.org/IDSSWebService/GetProductsResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetProductsAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetAllUsers", ReplyAction="http://tempuri.org/IDSSWebService/GetAllUsersResponse")]
        DSS_Website.DSS_Service.SVCUser[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetAllUsers", ReplyAction="http://tempuri.org/IDSSWebService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/Search", ReplyAction="http://tempuri.org/IDSSWebService/SearchResponse")]
        DSS_Website.DSS_Service.SVCProduct[] Search(string[] tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/Search", ReplyAction="http://tempuri.org/IDSSWebService/SearchResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SearchAsync(string[] tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AddUser", ReplyAction="http://tempuri.org/IDSSWebService/AddUserResponse")]
        int AddUser(DSS_Website.DSS_Service.SVCUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AddUser", ReplyAction="http://tempuri.org/IDSSWebService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(DSS_Website.DSS_Service.SVCUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/RemoveUser", ReplyAction="http://tempuri.org/IDSSWebService/RemoveUserResponse")]
        int RemoveUser(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/RemoveUser", ReplyAction="http://tempuri.org/IDSSWebService/RemoveUserResponse")]
        System.Threading.Tasks.Task<int> RemoveUserAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/DisableUser", ReplyAction="http://tempuri.org/IDSSWebService/DisableUserResponse")]
        int DisableUser(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/DisableUser", ReplyAction="http://tempuri.org/IDSSWebService/DisableUserResponse")]
        System.Threading.Tasks.Task<int> DisableUserAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EnableUser", ReplyAction="http://tempuri.org/IDSSWebService/EnableUserResponse")]
        int EnableUser(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EnableUser", ReplyAction="http://tempuri.org/IDSSWebService/EnableUserResponse")]
        System.Threading.Tasks.Task<int> EnableUserAsync(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EditUser", ReplyAction="http://tempuri.org/IDSSWebService/EditUserResponse")]
        int EditUser(DSS_Website.DSS_Service.SVCUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EditUser", ReplyAction="http://tempuri.org/IDSSWebService/EditUserResponse")]
        System.Threading.Tasks.Task<int> EditUserAsync(DSS_Website.DSS_Service.SVCUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AddProduct", ReplyAction="http://tempuri.org/IDSSWebService/AddProductResponse")]
        int AddProduct(DSS_Website.DSS_Service.SVCProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AddProduct", ReplyAction="http://tempuri.org/IDSSWebService/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(DSS_Website.DSS_Service.SVCProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/RemoveProduct", ReplyAction="http://tempuri.org/IDSSWebService/RemoveProductResponse")]
        int RemoveProduct(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/RemoveProduct", ReplyAction="http://tempuri.org/IDSSWebService/RemoveProductResponse")]
        System.Threading.Tasks.Task<int> RemoveProductAsync(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EditProduct", ReplyAction="http://tempuri.org/IDSSWebService/EditProductResponse")]
        int EditProduct(DSS_Website.DSS_Service.SVCProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EditProduct", ReplyAction="http://tempuri.org/IDSSWebService/EditProductResponse")]
        System.Threading.Tasks.Task<int> EditProductAsync(DSS_Website.DSS_Service.SVCProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/DisableProduct", ReplyAction="http://tempuri.org/IDSSWebService/DisableProductResponse")]
        int DisableProduct(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/DisableProduct", ReplyAction="http://tempuri.org/IDSSWebService/DisableProductResponse")]
        System.Threading.Tasks.Task<int> DisableProductAsync(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EnableProduct", ReplyAction="http://tempuri.org/IDSSWebService/EnableProductResponse")]
        int EnableProduct(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/EnableProduct", ReplyAction="http://tempuri.org/IDSSWebService/EnableProductResponse")]
        System.Threading.Tasks.Task<int> EnableProductAsync(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetProduct", ReplyAction="http://tempuri.org/IDSSWebService/GetProductResponse")]
        DSS_Website.DSS_Service.SVCProduct GetProduct(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetProduct", ReplyAction="http://tempuri.org/IDSSWebService/GetProductResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> GetProductAsync(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/MostSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/MostSellingProductResponse")]
        DSS_Website.DSS_Service.SVCProduct MostSellingProduct(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/MostSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/MostSellingProductResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> MostSellingProductAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/LeastSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/LeastSellingProductResponse")]
        DSS_Website.DSS_Service.SVCProduct LeastSellingProduct(string categoty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/LeastSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/LeastSellingProductResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> LeastSellingProductAsync(string categoty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/OverallMostSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/OverallMostSellingProductResponse")]
        DSS_Website.DSS_Service.SVCProduct OverallMostSellingProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/OverallMostSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/OverallMostSellingProductResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> OverallMostSellingProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/OverallLeastSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/OverallLeastSellingProductResponse")]
        DSS_Website.DSS_Service.SVCProduct OverallLeastSellingProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/OverallLeastSellingProduct", ReplyAction="http://tempuri.org/IDSSWebService/OverallLeastSellingProductResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> OverallLeastSellingProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetTax", ReplyAction="http://tempuri.org/IDSSWebService/GetTaxResponse")]
        double GetTax();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetTax", ReplyAction="http://tempuri.org/IDSSWebService/GetTaxResponse")]
        System.Threading.Tasks.Task<double> GetTaxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SetTax", ReplyAction="http://tempuri.org/IDSSWebService/SetTaxResponse")]
        void SetTax(double TAX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SetTax", ReplyAction="http://tempuri.org/IDSSWebService/SetTaxResponse")]
        System.Threading.Tasks.Task SetTaxAsync(double TAX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/Transact", ReplyAction="http://tempuri.org/IDSSWebService/TransactResponse")]
        int Transact(DSS_Website.DSS_Service.SVCUser user, DSS_Website.DSS_Service.SVCProduct[] products, float price, string paymentMethod, string delivery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/Transact", ReplyAction="http://tempuri.org/IDSSWebService/TransactResponse")]
        System.Threading.Tasks.Task<int> TransactAsync(DSS_Website.DSS_Service.SVCUser user, DSS_Website.DSS_Service.SVCProduct[] products, float price, string paymentMethod, string delivery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/ChangeUserPassword", ReplyAction="http://tempuri.org/IDSSWebService/ChangeUserPasswordResponse")]
        int ChangeUserPassword(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/ChangeUserPassword", ReplyAction="http://tempuri.org/IDSSWebService/ChangeUserPasswordResponse")]
        System.Threading.Tasks.Task<int> ChangeUserPasswordAsync(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetPointsDiscount", ReplyAction="http://tempuri.org/IDSSWebService/GetPointsDiscountResponse")]
        int GetPointsDiscount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetPointsDiscount", ReplyAction="http://tempuri.org/IDSSWebService/GetPointsDiscountResponse")]
        System.Threading.Tasks.Task<int> GetPointsDiscountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetAllOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetAllOrdersResponse")]
        DSS_Website.DSS_Service.SVCOrder[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetAllOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCOrder[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUserOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetUserOrdersResponse")]
        DSS_Website.DSS_Service.SVCOrder[] GetUserOrders(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUserOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetUserOrdersResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCOrder[]> GetUserOrdersAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetOrderItems", ReplyAction="http://tempuri.org/IDSSWebService/GetOrderItemsResponse")]
        DSS_Website.DSS_Service.SVCProduct[] GetOrderItems(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetOrderItems", ReplyAction="http://tempuri.org/IDSSWebService/GetOrderItemsResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetOrderItemsAsync(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetCategoryPerfomance", ReplyAction="http://tempuri.org/IDSSWebService/GetCategoryPerfomanceResponse")]
        double GetCategoryPerfomance(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetCategoryPerfomance", ReplyAction="http://tempuri.org/IDSSWebService/GetCategoryPerfomanceResponse")]
        System.Threading.Tasks.Task<double> GetCategoryPerfomanceAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetWorstBuyer", ReplyAction="http://tempuri.org/IDSSWebService/GetWorstBuyerResponse")]
        DSS_Website.DSS_Service.SVCUser GetWorstBuyer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetWorstBuyer", ReplyAction="http://tempuri.org/IDSSWebService/GetWorstBuyerResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetWorstBuyerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetBestBuyer", ReplyAction="http://tempuri.org/IDSSWebService/GetBestBuyerResponse")]
        DSS_Website.DSS_Service.SVCUser GetBestBuyer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetBestBuyer", ReplyAction="http://tempuri.org/IDSSWebService/GetBestBuyerResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetBestBuyerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetNumberOfSales", ReplyAction="http://tempuri.org/IDSSWebService/GetNumberOfSalesResponse")]
        int GetNumberOfSales(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetNumberOfSales", ReplyAction="http://tempuri.org/IDSSWebService/GetNumberOfSalesResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfSalesAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SalesContribution", ReplyAction="http://tempuri.org/IDSSWebService/SalesContributionResponse")]
        double SalesContribution(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SalesContribution", ReplyAction="http://tempuri.org/IDSSWebService/SalesContributionResponse")]
        System.Threading.Tasks.Task<double> SalesContributionAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/RevenuePerTransaction", ReplyAction="http://tempuri.org/IDSSWebService/RevenuePerTransactionResponse")]
        double[] RevenuePerTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/RevenuePerTransaction", ReplyAction="http://tempuri.org/IDSSWebService/RevenuePerTransactionResponse")]
        System.Threading.Tasks.Task<double[]> RevenuePerTransactionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetRevenue", ReplyAction="http://tempuri.org/IDSSWebService/GetRevenueResponse")]
        double GetRevenue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetRevenue", ReplyAction="http://tempuri.org/IDSSWebService/GetRevenueResponse")]
        System.Threading.Tasks.Task<double> GetRevenueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetTotalOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetTotalOrdersResponse")]
        int GetTotalOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetTotalOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetTotalOrdersResponse")]
        System.Threading.Tasks.Task<int> GetTotalOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetTotalUsers", ReplyAction="http://tempuri.org/IDSSWebService/GetTotalUsersResponse")]
        int GetTotalUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetTotalUsers", ReplyAction="http://tempuri.org/IDSSWebService/GetTotalUsersResponse")]
        System.Threading.Tasks.Task<int> GetTotalUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/TopFiveSelling", ReplyAction="http://tempuri.org/IDSSWebService/TopFiveSellingResponse")]
        DSS_Website.DSS_Service.SVCProduct[] TopFiveSelling();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/TopFiveSelling", ReplyAction="http://tempuri.org/IDSSWebService/TopFiveSellingResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> TopFiveSellingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByPriceAsc", ReplyAction="http://tempuri.org/IDSSWebService/SortByPriceAscResponse")]
        DSS_Website.DSS_Service.SVCProduct[] SortByPriceAsc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByPriceAsc", ReplyAction="http://tempuri.org/IDSSWebService/SortByPriceAscResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByPriceAscAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByPriceADesc", ReplyAction="http://tempuri.org/IDSSWebService/SortByPriceADescResponse")]
        DSS_Website.DSS_Service.SVCProduct[] SortByPriceADesc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByPriceADesc", ReplyAction="http://tempuri.org/IDSSWebService/SortByPriceADescResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByPriceADescAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByNameAZ", ReplyAction="http://tempuri.org/IDSSWebService/SortByNameAZResponse")]
        DSS_Website.DSS_Service.SVCProduct[] SortByNameAZ();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByNameAZ", ReplyAction="http://tempuri.org/IDSSWebService/SortByNameAZResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByNameAZAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByNameZA", ReplyAction="http://tempuri.org/IDSSWebService/SortByNameZAResponse")]
        DSS_Website.DSS_Service.SVCProduct[] SortByNameZA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/SortByNameZA", ReplyAction="http://tempuri.org/IDSSWebService/SortByNameZAResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByNameZAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AverageUsersPerDay", ReplyAction="http://tempuri.org/IDSSWebService/AverageUsersPerDayResponse")]
        double AverageUsersPerDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AverageUsersPerDay", ReplyAction="http://tempuri.org/IDSSWebService/AverageUsersPerDayResponse")]
        System.Threading.Tasks.Task<double> AverageUsersPerDayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/FilterOrders", ReplyAction="http://tempuri.org/IDSSWebService/FilterOrdersResponse")]
        int FilterOrders(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/FilterOrders", ReplyAction="http://tempuri.org/IDSSWebService/FilterOrdersResponse")]
        System.Threading.Tasks.Task<int> FilterOrdersAsync(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/FilterRevenue", ReplyAction="http://tempuri.org/IDSSWebService/FilterRevenueResponse")]
        double FilterRevenue(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/FilterRevenue", ReplyAction="http://tempuri.org/IDSSWebService/FilterRevenueResponse")]
        System.Threading.Tasks.Task<double> FilterRevenueAsync(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetFilteredOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetFilteredOrdersResponse")]
        DSS_Website.DSS_Service.SVCOrder[] GetFilteredOrders(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetFilteredOrders", ReplyAction="http://tempuri.org/IDSSWebService/GetFilteredOrdersResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCOrder[]> GetFilteredOrdersAsync(string timeframe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AddToWishList", ReplyAction="http://tempuri.org/IDSSWebService/AddToWishListResponse")]
        int AddToWishList(string productID, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/AddToWishList", ReplyAction="http://tempuri.org/IDSSWebService/AddToWishListResponse")]
        System.Threading.Tasks.Task<int> AddToWishListAsync(string productID, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUserWishlist", ReplyAction="http://tempuri.org/IDSSWebService/GetUserWishlistResponse")]
        DSS_Website.DSS_Service.SVCProduct[] GetUserWishlist(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetUserWishlist", ReplyAction="http://tempuri.org/IDSSWebService/GetUserWishlistResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetUserWishlistAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/TopFiveMostWishedItems", ReplyAction="http://tempuri.org/IDSSWebService/TopFiveMostWishedItemsResponse")]
        DSS_Website.DSS_Service.SVCProduct[] TopFiveMostWishedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/TopFiveMostWishedItems", ReplyAction="http://tempuri.org/IDSSWebService/TopFiveMostWishedItemsResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> TopFiveMostWishedItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetProspectiveBuyers", ReplyAction="http://tempuri.org/IDSSWebService/GetProspectiveBuyersResponse")]
        DSS_Website.DSS_Service.SVCUser[] GetProspectiveBuyers(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDSSWebService/GetProspectiveBuyers", ReplyAction="http://tempuri.org/IDSSWebService/GetProspectiveBuyersResponse")]
        System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser[]> GetProspectiveBuyersAsync(string productID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDSSWebServiceChannel : DSS_Website.DSS_Service.IDSSWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DSSWebServiceClient : System.ServiceModel.ClientBase<DSS_Website.DSS_Service.IDSSWebService>, DSS_Website.DSS_Service.IDSSWebService {
        
        public DSSWebServiceClient() {
        }
        
        public DSSWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DSSWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSSWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSSWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DSS_Website.DSS_Service.SVCUser GetUser(string email, string password) {
            return base.Channel.GetUser(email, password);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetUserAsync(string email, string password) {
            return base.Channel.GetUserAsync(email, password);
        }
        
        public DSS_Website.DSS_Service.SVCUser GetUserByID(string userID) {
            return base.Channel.GetUserByID(userID);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetUserByIDAsync(string userID) {
            return base.Channel.GetUserByIDAsync(userID);
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] GetProducts(string category) {
            return base.Channel.GetProducts(category);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetProductsAsync(string category) {
            return base.Channel.GetProductsAsync(category);
        }
        
        public DSS_Website.DSS_Service.SVCUser[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] Search(string[] tags) {
            return base.Channel.Search(tags);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SearchAsync(string[] tags) {
            return base.Channel.SearchAsync(tags);
        }
        
        public int AddUser(DSS_Website.DSS_Service.SVCUser user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(DSS_Website.DSS_Service.SVCUser user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public int RemoveUser(string userID) {
            return base.Channel.RemoveUser(userID);
        }
        
        public System.Threading.Tasks.Task<int> RemoveUserAsync(string userID) {
            return base.Channel.RemoveUserAsync(userID);
        }
        
        public int DisableUser(string userID) {
            return base.Channel.DisableUser(userID);
        }
        
        public System.Threading.Tasks.Task<int> DisableUserAsync(string userID) {
            return base.Channel.DisableUserAsync(userID);
        }
        
        public int EnableUser(string UserID) {
            return base.Channel.EnableUser(UserID);
        }
        
        public System.Threading.Tasks.Task<int> EnableUserAsync(string UserID) {
            return base.Channel.EnableUserAsync(UserID);
        }
        
        public int EditUser(DSS_Website.DSS_Service.SVCUser user) {
            return base.Channel.EditUser(user);
        }
        
        public System.Threading.Tasks.Task<int> EditUserAsync(DSS_Website.DSS_Service.SVCUser user) {
            return base.Channel.EditUserAsync(user);
        }
        
        public int AddProduct(DSS_Website.DSS_Service.SVCProduct product) {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(DSS_Website.DSS_Service.SVCProduct product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public int RemoveProduct(string productID) {
            return base.Channel.RemoveProduct(productID);
        }
        
        public System.Threading.Tasks.Task<int> RemoveProductAsync(string productID) {
            return base.Channel.RemoveProductAsync(productID);
        }
        
        public int EditProduct(DSS_Website.DSS_Service.SVCProduct product) {
            return base.Channel.EditProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> EditProductAsync(DSS_Website.DSS_Service.SVCProduct product) {
            return base.Channel.EditProductAsync(product);
        }
        
        public int DisableProduct(string productID) {
            return base.Channel.DisableProduct(productID);
        }
        
        public System.Threading.Tasks.Task<int> DisableProductAsync(string productID) {
            return base.Channel.DisableProductAsync(productID);
        }
        
        public int EnableProduct(string productID) {
            return base.Channel.EnableProduct(productID);
        }
        
        public System.Threading.Tasks.Task<int> EnableProductAsync(string productID) {
            return base.Channel.EnableProductAsync(productID);
        }
        
        public DSS_Website.DSS_Service.SVCProduct GetProduct(string productID) {
            return base.Channel.GetProduct(productID);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> GetProductAsync(string productID) {
            return base.Channel.GetProductAsync(productID);
        }
        
        public DSS_Website.DSS_Service.SVCProduct MostSellingProduct(string category) {
            return base.Channel.MostSellingProduct(category);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> MostSellingProductAsync(string category) {
            return base.Channel.MostSellingProductAsync(category);
        }
        
        public DSS_Website.DSS_Service.SVCProduct LeastSellingProduct(string categoty) {
            return base.Channel.LeastSellingProduct(categoty);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> LeastSellingProductAsync(string categoty) {
            return base.Channel.LeastSellingProductAsync(categoty);
        }
        
        public DSS_Website.DSS_Service.SVCProduct OverallMostSellingProduct() {
            return base.Channel.OverallMostSellingProduct();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> OverallMostSellingProductAsync() {
            return base.Channel.OverallMostSellingProductAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct OverallLeastSellingProduct() {
            return base.Channel.OverallLeastSellingProduct();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct> OverallLeastSellingProductAsync() {
            return base.Channel.OverallLeastSellingProductAsync();
        }
        
        public double GetTax() {
            return base.Channel.GetTax();
        }
        
        public System.Threading.Tasks.Task<double> GetTaxAsync() {
            return base.Channel.GetTaxAsync();
        }
        
        public void SetTax(double TAX) {
            base.Channel.SetTax(TAX);
        }
        
        public System.Threading.Tasks.Task SetTaxAsync(double TAX) {
            return base.Channel.SetTaxAsync(TAX);
        }
        
        public int Transact(DSS_Website.DSS_Service.SVCUser user, DSS_Website.DSS_Service.SVCProduct[] products, float price, string paymentMethod, string delivery) {
            return base.Channel.Transact(user, products, price, paymentMethod, delivery);
        }
        
        public System.Threading.Tasks.Task<int> TransactAsync(DSS_Website.DSS_Service.SVCUser user, DSS_Website.DSS_Service.SVCProduct[] products, float price, string paymentMethod, string delivery) {
            return base.Channel.TransactAsync(user, products, price, paymentMethod, delivery);
        }
        
        public int ChangeUserPassword(string username, string oldPassword, string newPassword) {
            return base.Channel.ChangeUserPassword(username, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<int> ChangeUserPasswordAsync(string username, string oldPassword, string newPassword) {
            return base.Channel.ChangeUserPasswordAsync(username, oldPassword, newPassword);
        }
        
        public int GetPointsDiscount() {
            return base.Channel.GetPointsDiscount();
        }
        
        public System.Threading.Tasks.Task<int> GetPointsDiscountAsync() {
            return base.Channel.GetPointsDiscountAsync();
        }
        
        public DSS_Website.DSS_Service.SVCOrder[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCOrder[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public DSS_Website.DSS_Service.SVCOrder[] GetUserOrders(string userID) {
            return base.Channel.GetUserOrders(userID);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCOrder[]> GetUserOrdersAsync(string userID) {
            return base.Channel.GetUserOrdersAsync(userID);
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] GetOrderItems(string orderID) {
            return base.Channel.GetOrderItems(orderID);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetOrderItemsAsync(string orderID) {
            return base.Channel.GetOrderItemsAsync(orderID);
        }
        
        public double GetCategoryPerfomance(string category) {
            return base.Channel.GetCategoryPerfomance(category);
        }
        
        public System.Threading.Tasks.Task<double> GetCategoryPerfomanceAsync(string category) {
            return base.Channel.GetCategoryPerfomanceAsync(category);
        }
        
        public DSS_Website.DSS_Service.SVCUser GetWorstBuyer() {
            return base.Channel.GetWorstBuyer();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetWorstBuyerAsync() {
            return base.Channel.GetWorstBuyerAsync();
        }
        
        public DSS_Website.DSS_Service.SVCUser GetBestBuyer() {
            return base.Channel.GetBestBuyer();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser> GetBestBuyerAsync() {
            return base.Channel.GetBestBuyerAsync();
        }
        
        public int GetNumberOfSales(string category) {
            return base.Channel.GetNumberOfSales(category);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfSalesAsync(string category) {
            return base.Channel.GetNumberOfSalesAsync(category);
        }
        
        public double SalesContribution(string category) {
            return base.Channel.SalesContribution(category);
        }
        
        public System.Threading.Tasks.Task<double> SalesContributionAsync(string category) {
            return base.Channel.SalesContributionAsync(category);
        }
        
        public double[] RevenuePerTransaction() {
            return base.Channel.RevenuePerTransaction();
        }
        
        public System.Threading.Tasks.Task<double[]> RevenuePerTransactionAsync() {
            return base.Channel.RevenuePerTransactionAsync();
        }
        
        public double GetRevenue() {
            return base.Channel.GetRevenue();
        }
        
        public System.Threading.Tasks.Task<double> GetRevenueAsync() {
            return base.Channel.GetRevenueAsync();
        }
        
        public int GetTotalOrders() {
            return base.Channel.GetTotalOrders();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalOrdersAsync() {
            return base.Channel.GetTotalOrdersAsync();
        }
        
        public int GetTotalUsers() {
            return base.Channel.GetTotalUsers();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalUsersAsync() {
            return base.Channel.GetTotalUsersAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] TopFiveSelling() {
            return base.Channel.TopFiveSelling();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> TopFiveSellingAsync() {
            return base.Channel.TopFiveSellingAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] SortByPriceAsc() {
            return base.Channel.SortByPriceAsc();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByPriceAscAsync() {
            return base.Channel.SortByPriceAscAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] SortByPriceADesc() {
            return base.Channel.SortByPriceADesc();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByPriceADescAsync() {
            return base.Channel.SortByPriceADescAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] SortByNameAZ() {
            return base.Channel.SortByNameAZ();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByNameAZAsync() {
            return base.Channel.SortByNameAZAsync();
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] SortByNameZA() {
            return base.Channel.SortByNameZA();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> SortByNameZAAsync() {
            return base.Channel.SortByNameZAAsync();
        }
        
        public double AverageUsersPerDay() {
            return base.Channel.AverageUsersPerDay();
        }
        
        public System.Threading.Tasks.Task<double> AverageUsersPerDayAsync() {
            return base.Channel.AverageUsersPerDayAsync();
        }
        
        public int FilterOrders(string timeframe) {
            return base.Channel.FilterOrders(timeframe);
        }
        
        public System.Threading.Tasks.Task<int> FilterOrdersAsync(string timeframe) {
            return base.Channel.FilterOrdersAsync(timeframe);
        }
        
        public double FilterRevenue(string timeframe) {
            return base.Channel.FilterRevenue(timeframe);
        }
        
        public System.Threading.Tasks.Task<double> FilterRevenueAsync(string timeframe) {
            return base.Channel.FilterRevenueAsync(timeframe);
        }
        
        public DSS_Website.DSS_Service.SVCOrder[] GetFilteredOrders(string timeframe) {
            return base.Channel.GetFilteredOrders(timeframe);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCOrder[]> GetFilteredOrdersAsync(string timeframe) {
            return base.Channel.GetFilteredOrdersAsync(timeframe);
        }
        
        public int AddToWishList(string productID, string userID) {
            return base.Channel.AddToWishList(productID, userID);
        }
        
        public System.Threading.Tasks.Task<int> AddToWishListAsync(string productID, string userID) {
            return base.Channel.AddToWishListAsync(productID, userID);
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] GetUserWishlist(string userID) {
            return base.Channel.GetUserWishlist(userID);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> GetUserWishlistAsync(string userID) {
            return base.Channel.GetUserWishlistAsync(userID);
        }
        
        public DSS_Website.DSS_Service.SVCProduct[] TopFiveMostWishedItems() {
            return base.Channel.TopFiveMostWishedItems();
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCProduct[]> TopFiveMostWishedItemsAsync() {
            return base.Channel.TopFiveMostWishedItemsAsync();
        }
        
        public DSS_Website.DSS_Service.SVCUser[] GetProspectiveBuyers(string productID) {
            return base.Channel.GetProspectiveBuyers(productID);
        }
        
        public System.Threading.Tasks.Task<DSS_Website.DSS_Service.SVCUser[]> GetProspectiveBuyersAsync(string productID) {
            return base.Channel.GetProspectiveBuyersAsync(productID);
        }
    }
}
